1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
array_bidimensional = np.random.randint(34, 99, size=(4, 3))  # sitaxis (low, hig, size, dtype) ???????
print("Array aleatorio:\n", array_bidimensional)

Array aleatorio:
 [[87 81 71]
 [77 44 54]
 [51 40 38]
 [91 61 79]]


In [4]:
print("Número de dimensiones (ndim):",array_bidimensional.ndim)
print("Tipo de datos (dtype):", array_bidimensional.dtype)

Número de dimensiones (ndim): 2
Tipo de datos (dtype): int32


2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

Las listas para crear los arrays son las siguientes

In [5]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [6]:
array1D = np.array(lista1)

In [7]:
array1D

array([34, 56, 71, 98, 10])

In [8]:
array2D = np.array(lista2)

In [9]:
array2D

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

El primer elemento.

Lo elementos que están en posición impar.

Los cuatro primeros elementos.

Los últimos tres elementos.

Los elementos entre el 4 y el 8 (incluido).

In [10]:
array_50 = np.arange(50)    #### BUSCAR OTRO MÉTODO 
print(f"Array arange(50):\n{array_50}\n")

Array arange(50):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]



In [11]:
print("Primer elemento del array_50:", array_50[0])

Primer elemento del array_50: 0


In [12]:
print("Elementos en posición impar array_50:", array_50[1::2])  ## SIN COMAS PARA INDICAR UNA DIMENSIÓN. el salto lo marca :2

Elementos en posición impar array_50: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [13]:
print(array_50.ndim)

1


In [14]:
print("Primeros tres elementos de array_50:", array_50[:4])

Primeros tres elementos de array_50: [0 1 2 3]


In [15]:
print("Elementos en posición impar array_50:", array_50[-3::])

Elementos en posición impar array_50: [47 48 49]


In [16]:
print("Elementos en posición impar array_50:", array_50[3:9])

Elementos en posición impar array_50: [3 4 5 6 7 8]


4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

La primera fila y todas las columnas.

Todas las filas pares.

La primera columna y todas las filas

In [17]:
array_bidimensional_2 = np.random.randint(34, 99, size=(4, 5))  # sitaxis (low, hig, size, dtype) ???????
print("Array bidimensional 2:\n", array_bidimensional_2)

Array bidimensional 2:
 [[81 70 59 98 95]
 [61 43 40 86 86]
 [53 63 98 95 50]
 [81 90 40 76 82]]


In [18]:
# primera fila y todas las columnas:

array_bidimensional_2[0, :]

array([81, 70, 59, 98, 95])

In [19]:
# Todas las filas pares
array_bidimensional_2[:,::2]

array([[81, 59, 95],
       [61, 40, 86],
       [53, 98, 50],
       [81, 40, 82]])

In [20]:
array_bidimensional_2[::2]

array([[81, 70, 59, 98, 95],
       [53, 63, 98, 95, 50]])

In [21]:
array_bidimensional_2[::2, ::]  #::2, en el eje de las filas, selecciona una sí, una no: emieza en la fila 0, luego la 2, 4 etc..
# :: en el eje de las columnas, selecciona todas las columnas sin saltos.

array([[81, 70, 59, 98, 95],
       [53, 63, 98, 95, 50]])

In [22]:
array_bidimensional_2

array([[81, 70, 59, 98, 95],
       [61, 43, 40, 86, 86],
       [53, 63, 98, 95, 50],
       [81, 90, 40, 76, 82]])

In [23]:
# La primera columna y todas las filas
array_bidimensional_2[:, 0]

array([81, 61, 53, 81])

5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [24]:
array_bidimensional_20 = np.random.randint(0, 51, size=(4, 5))  # sitaxis (low, hig, size, dtype) ???????
print("Array bidimensional 20:\n", array_bidimensional_20)

Array bidimensional 20:
 [[15 40 36  3 23]
 [43  5 40 44 44]
 [ 5 36 28 19  3]
 [48 27 28 30 41]]


In [25]:
# Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo"
mascara = np.where((array_bidimensional_20 > 30) | (array_bidimensional_20 < 10), "objetivo", "no es mi objetivo")
mascara

array([['no es mi objetivo', 'objetivo', 'objetivo', 'objetivo',
        'no es mi objetivo'],
       ['objetivo', 'objetivo', 'objetivo', 'objetivo', 'objetivo'],
       ['objetivo', 'objetivo', 'no es mi objetivo', 'no es mi objetivo',
        'objetivo'],
       ['objetivo', 'no es mi objetivo', 'no es mi objetivo',
        'no es mi objetivo', 'objetivo']], dtype='<U17')

In [40]:
# Los valores de mi array bidimensional multiplicalos por el escalar 10.
escalar = 10
array_bidimensional_20 * escalar



array([[150, 400, 360,  30, 230],
       [430,  50, 400, 440, 440],
       [ 50, 360, 280, 190,  30],
       [480, 270, 280, 300, 410]])

6. Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

Suma el primer array con el segundo.

Aplicar la potencia para el primer array elevado al segundo.

In [41]:
array_bidimensional_101 = np.random.randint(0, 101, size=(4, 5))  # sitaxis (low, hig, size, dtype) ???????
print("Array bidimensional 101:\n", array_bidimensional_101)

Array bidimensional 101:
 [[13 87 49 74 66]
 [75  3 23 41 18]
 [10 96 57 41 21]
 [54 90 10 44 99]]


In [43]:
# Suma el primer array con el segundo.
np.add(array_bidimensional_20, array_bidimensional_101)
suma = (array_bidimensional_101 + array_bidimensional_20)
print(suma)

[[ 28 127  85  77  89]
 [118   8  63  85  62]
 [ 15 132  85  60  24]
 [102 117  38  74 140]]


In [29]:
# Aplicar la potencia para el primer array elevado al segundo.    ??????????????????????????????????
potencia = np.power(array_bidimensional_20, array_bidimensional_101)
potencia

array([[ -639314417,   671088640,           0, -1669737407,  -312445961],
       [ -225877909,  -613187947,   631242752,           0,           0],
       [  -99612771,           0, -1073741824,   454459353,  1870418611],
       [          0,  -869015695,           0,           0,   622828497]])


## 7Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

Calcula:

La media de los elementos

La media de las columnas y redondéalo a dos decimales

El valor máximo de cada fila

El valor mínimo de cada fila

Hay algun valor que sea mayor que 90 en tu array

Donde los podemos encontrar, cuáles son sus índices

Ordena el array de mayor a menor

In [30]:
array_bidimensional_101 = np.random.randint(0, 101, size=(4, 5))  # sitaxis (low, hig, size, dtype) ???????
print("Array bidimensional 101:\n", array_bidimensional_101)

Array bidimensional 101:
 [[10 70 62 33 20]
 [51 57 76 75 67]
 [75 63 76 15 30]
 [76  1 10  0  4]]


In [31]:
# La media de los elementos
array_bidimensional_101_media = np.mean(array_bidimensional_101)
array_bidimensional_101_media

43.55

In [32]:
# La media de las columnas y redondéalo a dos decimales
#axis = 0; columnas
#axis =1; filas
array_bidimensional_101_media_columnas = array_bidimensional_101.mean(axis=0)
array_bidimensional_101_media_columnas

array([53.  , 47.75, 56.  , 30.75, 30.25])

In [33]:
redondear_array_bidimensional_101_decimales = array_bidimensional_101_media_columnas.round(2) # ??????????
redondear_array_bidimensional_101_decimales

array([53.  , 47.75, 56.  , 30.75, 30.25])

In [34]:
# El valor máximo de cada fila
array_bidimensional_101_max = array_bidimensional_101.max(axis=1)
array_bidimensional_101_max


array([70, 76, 76, 76])

In [35]:
# El valor mínimo de cada fila
array_bidimensional_101_min = array_bidimensional_101.min(axis=1)
array_bidimensional_101_min

array([10, 51, 15,  0])

In [36]:
# Hay algun valor que sea mayor que 90 en tu array
array_bidimensional_101_90 = array_bidimensional_101[array_bidimensional_101 > 90] 
array_bidimensional_101_90

array([], dtype=int32)

In [37]:
# Donde los podemos encontrar, cuáles son sus índices
indices_mayores_90 = np.where(array_bidimensional_101 > 90)
print("Índices donde los valores son mayores a 90:", indices_mayores_90)

Índices donde los valores son mayores a 90: (array([], dtype=int64), array([], dtype=int64))


In [38]:
# Ordena el array de menor a mayor
ordenado = np.sort(array_bidimensional_101) # Por defecto ordena por filas
ordenado

array([[10, 20, 33, 62, 70],
       [51, 57, 67, 75, 76],
       [15, 30, 63, 75, 76],
       [ 0,  1,  4, 10, 76]])

In [39]:
# Primero le ordenamos y luego le damos la vuelta
ordenado[:, ::-1] # todas las filas, todas las columnas, en pasos de -1

array([[70, 62, 33, 20, 10],
       [76, 75, 67, 57, 51],
       [76, 75, 63, 30, 15],
       [76, 10,  4,  1,  0]])